openapi: 3.0.0
info:
  title: 'Laravel OpenApi Demo Documentation'
  description: 'L5 Swagger OpenApi description'
  contact:
    email: admin@admin.com
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8001/api'
    description: 'Demo API Server'
paths:
  /posts:
    get:
      tags:
        - Posts
      summary: 'Get list of posts'
      description: 'Returns list of posts'
      operationId: getPostList
      responses:
        200:
          description: 'Successful operation'
        401:
          description: Unauthenticated
        403:
          description: Forbidden
tags:
  -
    name: Products
    description: 'API Endpoints of Products'
